"""
Workflow search module.

Provides a SQLite-backed persistence layer for workflows and a
search API.
"""

import json
import sqlite3
from pathlib import Path
from typing import List, Dict, Any, Optional

# Determine DB path relative to this file
DB_PATH = Path(__file__).resolve().parent.parent / "data" / "workflows.db"

def _get_connection() -> sqlite3.Connection:
    """
    Ensure the database directory exists and return a connection.
    """
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(DB_PATH))
    conn.row_factory = sqlite3.Row # Enable column access by name
    return conn

def init_db() -> None:
    """
    Initialise the database using the SQL schema.
    """
    sql_path = Path(__file__).resolve().parent / "workflow_database.sql"
    if not sql_path.exists():
        raise FileNotFoundError(f"Missing schema file: {sql_path}")

    conn = _get_connection()
    try:
        with conn:
            # Use executescript to run multiple statements safely
            conn.executescript(sql_path.read_text(encoding="utf-8"))
    finally:
        conn.close()

def add_workflow(
    name: str,
    description: str,
    steps: List[str],
    documentation_url: Optional[str] = None,
) -> int:
    """
    Persist a new workflow and return its autogenerated ID.
    """
    conn = _get_connection()
    # Serialize steps to JSON to handle commas/special chars in step names
    steps_json = json.dumps(steps)
    
    try:
        with conn:
            cur = conn.execute(
                """
                INSERT INTO workflows (name, description, steps, documentation_url)
                VALUES (?, ?, ?, ?)
                """,
                (name, description, steps_json, documentation_url),
            )
            return cur.lastrowid
    finally:
        conn.close()

def search_workflows(query: str) -> List[Dict[str, Any]]:
    """
    Search workflows by name or description.
    Returns a list of dicts with workflow fields.
    """
    conn = _get_connection()
    try:
        like_pattern = f"%{query}%"
        cur = conn.execute(
            """
            SELECT id, name, description, steps, documentation_url
            FROM workflows
            WHERE name LIKE ? OR description LIKE ?
            ORDER BY name
            """,
            (like_pattern, like_pattern),
        )
        rows = cur.fetchall()

        results = []
        for row in rows:
            # Deserialize steps from JSON
            steps_data = json.loads(row["steps"]) if row["steps"] else []
            
            results.append(
                {
                    "id": row["id"],
                    "name": row["name"],
                    "description": row["description"],
                    "steps": steps_data,
                    "documentation_url": row["documentation_url"],
                }
            )
        return results
    finally:
        conn.close()