package com.axentx.surrogate1.ui.model;

public class SignatureDrift {
    private String id;
    private String severity;      // e.g. HIGH, MEDIUM, LOW
    private String timestamp;    // ISO‑8601 UTC
    private String description;
    private boolean acknowledged;
    private boolean remediated;

    public SignatureDrift(String id, String severity, String timestamp, String description) {
        this.id = id;
        this.severity = severity;
        this.timestamp = timestamp;
        this.description = description;
        this.acknowledged = false;
        this.remediated = false;
    }

    // ----- getters & setters (generated by IDE or Lombok) -----
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }

    public String getSeverity() { return severity; }
    public void setSeverity(String severity) { this.severity = severity; }

    public String getTimestamp() { return timestamp; }
    public void setTimestamp(String timestamp) { this.timestamp = timestamp; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public boolean isAcknowledged() { return acknowledged; }
    public void setAcknowledged(boolean acknowledged) { this.acknowledged = acknowledged; }

    public boolean isRemediated() { return remediated; }
    public void setRemediated(boolean remediated) { this.remediated = remediated; }
}