import { Action, ActionContext } from '../interfaces';
import { LlmClient, LlmResponse } from '../../llm';
import { Logger } from '../../utils';
import { LlmCostInfo } from '../models/LlmCostInfo';

/**
 * Result shape for an LLM action – includes the generated text and the cost payload.
 */
export interface LlmActionResult {
  /** The raw text generated by the LLM */
  output: string;
  /** Cost metrics for this invocation */
  cost: LlmCostInfo;
}

/**
 * LlmAction executes a request against a configured LLM client and returns both
 * the generated output and a cost payload (tokens + USD). The payload is used
 * by the workflow engine and UI panels to display budgeting information.
 */
export class LlmAction implements Action<LlmActionResult> {
  private readonly client: LlmClient;
  private readonly logger: Logger;

  constructor(client: LlmClient, logger: Logger) {
    this.client = client;
    this.logger = logger;
  }

  /**
   * Executes the LLM request.
   *
   * @param ctx    Execution context supplied by the workflow engine.
   * @param prompt Prompt to send to the LLM.
   * @param model  Optional model identifier (defaults to the client’s default).
   * @returns      An object containing the generated text and cost information.
   */
  async execute(
    ctx: ActionContext,
    prompt: string,
    model?: string,
  ): Promise<LlmActionResult> {
    this.logger.debug('LlmAction.execute', { prompt, model });

    const response: LlmResponse = await this.client.generate({
      model,
      prompt,
    });

    // The provider (OpenAI, Anthropic, etc.) usually returns a `usage` block.
    const usage = response.usage ?? {
      prompt_tokens: 0,
      completion_tokens: 0,
      total_tokens: 0,
    };

    const cost = this.computeCost(model ?? this.client.defaultModel, usage);

    return {
      output: response.text,
      cost,
    };
  }

  /**
   * Computes the USD cost based on model pricing and token usage.
   *
   * Pricing is expressed per 1 000 tokens. If a model is not recognised,
   * the fallback pricing for `gpt-3.5-turbo` is used.
   *
   * @param model The model name used for the request.
   * @param usage Token usage data returned by the LLM provider.
   */
  private computeCost(
    model: string,
    usage: {
      prompt_tokens: number;
      completion_tokens: number;
      total_tokens: number;
    },
  ): LlmCostInfo {
    // -----------------------------------------------------------------------
    // 1️⃣  Pricing table – keep this in sync with your provider’s public rates.
    // -----------------------------------------------------------------------
    const PRICING: Record<
      string,
      { promptPer1k: number; completionPer1k: number }
    > = {
      // OpenAI pricing (as of 2024‑06)
      'gpt-3.5-turbo': { promptPer1k: 0.002, completionPer1k: 0.002 },
      'gpt-4': { promptPer1k: 0.03, completionPer1k: 0.06 },
      // Add more models here as needed.
    };

    const price = PRICING[model] ?? PRICING['gpt-3.5-turbo']; // safe fallback

    const costUsd =
      (usage.prompt_tokens * price.promptPer1k +
        usage.completion_tokens * price.completionPer1k) /
      1000;

    return {
      promptTokens: usage.prompt_tokens,
      completionTokens: usage.completion_tokens,
      totalTokens: usage.total_tokens,
      costUsd,
    };
  }
}