# /opt/axentx/surrogate-1/src/main/resources/application.properties
server.connection-timeout=1000
server.tomcat.keep-alive-timeout=30000
server.tomcat.max-keep-alive-requests=-1
server.servlet.session.timeout=1800