from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.dialects.sqlite import JSON
from datetime import datetime

db = SQLAlchemy()

class Alert(db.Model):
    """Core alert generated by the monitoring system."""
    __tablename__ = "alert"

    id = db.Column(db.Integer, primary_key=True)
    severity = db.Column(db.String(20), nullable=False)
    message = db.Column(db.String(255), nullable=False)
    # add any other fields you already have (timestamp, source, etc.)

    # One‑to‑many relationship to DecisionArtifact
    artifacts = db.relationship(
        "DecisionArtifact",
        back_populates="alert",
        cascade="all, delete-orphan",
        lazy="joined",
    )

    def __repr__(self):
        return f"<Alert {self.id} ({self.severity})>"


class DecisionArtifact(db.Model):
    """Container for all contextual information that helped decide what to do with an alert."""
    __tablename__ = "decision_artifact"

    id = db.Column(db.Integer, primary_key=True)
    alert_id = db.Column(db.Integer, db.ForeignKey("alert.id"), nullable=False)

    # JSON list of tags – e.g. ["network", "critical", "customer‑X"]
    context_tags = db.Column(JSON, nullable=False, default=list)

    # One‑to‑many relationship to DecisionLog entries
    logs = db.relationship(
        "DecisionLog",
        back_populates="artifact",
        cascade="all, delete-orphan",
        lazy="joined",
    )

    alert = db.relationship("Alert", back_populates="artifacts")

    def __repr__(self):
        return f"<DecisionArtifact {self.id} for Alert {self.alert_id}>"


class DecisionLog(db.Model):
    """A single human‑readable log entry that explains a decision step."""
    __tablename__ = "decision_log"

    id = db.Column(db.Integer, primary_key=True)
    artifact_id = db.Column(
        db.Integer, db.ForeignKey("decision_artifact.id"), nullable=False
    )
    timestamp = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    author = db.Column(db.String(80), nullable=True)          # optional
    message = db.Column(db.String(300), nullable=False)

    artifact = db.relationship("DecisionArtifact", back_populates="logs")

    def __repr__(self):
        return f"<DecisionLog {self.id} ({self.timestamp})>"