"""
multi_gpu_bridge – a lightweight shim that ships a deterministic
placeholder firmware binary for the multi‑GPU bridge.

The binary is generated by :func:`generate_firmware` and can be
accessed via ``importlib.resources``:

>>> from importlib import resources
>>> with resources.open_binary('multi_gpu_bridge', 'firmware.bin') as f:
...     data = f.read()
"""

# Re‑export the public helpers so callers can do:
#   from multi_gpu_bridge import generate_firmware, read_firmware
from .generate_firmware import generate_firmware, read_firmware, validate_firmware