import {
  Entity,
  PrimaryKey,
  Property,
  SerializedPrimaryKey,
  Index,
  Unique,
} from '@mikro-orm/core';

@Entity({ tableName: 'workflows' })
@Unique({ properties: ['name', 'version'] })
export class Workflow {
  @PrimaryKey()
  id!: string; // UUID, generated by DB

  @Property()
  @Index()
  name!: string;

  @Property({ nullable: true })
  description?: string | null;

  @Property({ type: 'json' })
  inputs: unknown = {};

  @Property({ type: 'json' })
  steps: unknown = [];

  @Property({ type: 'json' })
  outputs: unknown = {};

  @Property()
  version: number = 1;

  @Property({ onCreate: () => new Date() })
  createdAt = new Date();

  @Property({ onUpdate: () => new Date() })
  updatedAt = new Date();
}