replicaCount: 1

image:
  repository: axentx/surrogate-1
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}