from __future__ import annotations

from decimal import Decimal
from typing import Any

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Numeric,
    String,
    Text,
    func,
    Index,
)
from .base import Base


class CostRecommendation(Base):
    """
    Represents a single cost‑optimization recommendation generated by the
    analytics engine.

    The table is deliberately denormalised – each row is self‑contained and
    can be displayed in a UI without extra joins.
    """

    __tablename__ = "cost_recommendations"

    # ------------------------------------------------------------------ columns
    id = Column(Integer, primary_key=True, autoincrement=True)
    resource_id = Column(String(255), nullable=False)
    resource_type = Column(String(255), nullable=False)
    recommendation_type = Column(String(255), nullable=False)
    current_configuration = Column(Text, nullable=False)
    recommended_configuration = Column(Text, nullable=False)
    estimated_savings = Column(Numeric(12, 2), nullable=False)  # stored as Decimal
    actionable = Column(Boolean, nullable=False, server_default="false")
    created_at = Column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at = Column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    # ------------------------------------------------------------------ indexes
    __table_args__ = (
        Index(
            "idx_cost_recommendations_resource",
            "resource_id",
            "resource_type",
        ),
        Index("idx_cost_recommendations_actionable", "actionable"),
    )

    # ------------------------------------------------------------------ helpers
    def __repr__(self) -> str:
        # id may be None before the object is persisted
        return (
            f"<CostRecommendation(id={self.id!r}, "
            f"resource_id={self.resource_id!r}, "
            f"recommendation_type={self.recommendation_type!r})>"
        )

    # ------------------------------------------------------------------ type‑casting helpers
    @property
    def savings(self) -> Decimal:
        """Convenient accessor that always returns a Decimal."""
        return Decimal(self.estimated_savings)

    def as_dict(self) -> dict[str, Any]:
        """Serialise for JSON APIs – excludes internal SQLAlchemy state."""
        return {
            "id": self.id,
            "resource_id": self.resource_id,
            "resource_type": self.resource_type,
            "recommendation_type": self.recommendation_type,
            "current_configuration": self.current_configuration,
            "recommended_configuration": self.recommended_configuration,
            "estimated_savings": float(self.estimated_savings),
            "actionable": self.actionable,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }