//! Credit model – persisted with `sqlx`, exposed via JSON APIs.
//! Includes the optional low‑balance alert threshold and helper methods.

use serde::{Deserialize, Serialize};
use sqlx::{FromRow, Type};
use uuid::Uuid;

/// A credit balance belonging to an account.
///
/// The struct is stored in the `credits` table (see migration above) and
/// serialised for HTTP responses.  `alert_threshold` is `NULL` when the user
/// has not configured a low‑balance warning.
#[derive(Debug, Clone, Serialize, Deserialize, FromRow, Type)]
#[sqlx(type_name = "credits")] // optional, helps with compile‑time checks
pub struct Credit {
    /// Primary key – auto‑generated by the DB.
    pub id: i64,

    /// The account this credit belongs to.
    pub account_id: i64,

    /// Current bulk‑credit balance (positive = credit, negative = debt).
    pub bulk_balance: i64,

    /// Optional low‑balance alert threshold.
    ///
    /// * `None` → no alert.
    /// * `Some(v)` → fire an alert when `bulk_balance < v`.
    pub alert_threshold: Option<i64>,
}

impl Credit {
    /// Constructor used by repository code.  All fields are required
    /// except `alert_threshold`, which defaults to `None`.
    pub fn new(id: i64, account_id: i64, bulk_balance: i64) -> Self {
        Self {
            id,
            account_id,
            bulk_balance,
            alert_threshold: None,
        }
    }

    /// Returns `true` when the balance is below the configured threshold.
    /// If the threshold is `None` the function returns `false`.
    pub fn is_below_threshold(&self) -> bool {
        match self.alert_threshold {
            Some(th) => self.bulk_balance < th,
            None => false,
        }
    }

    /// Set (or clear) the low‑balance alert threshold.
    ///
    /// * `Some(v)` – enable the alert at `v`.
    /// * `None` – disable the alert for this credit.
    pub fn set_alert_threshold(&mut self, threshold: Option<i64>) {
        self.alert_threshold = threshold;
    }

    /// Convenience wrapper that accepts a plain `i64` and enables the alert.
    pub fn enable_alert(&mut self, threshold: i64) {
        self.alert_threshold = Some(threshold);
    }

    /// Convenience wrapper that disables the alert.
    pub fn disable_alert(&mut self) {
        self.alert_threshold = None;
    }
}