/**
 * Token‑ and USD‑level cost information for a single LLM invocation.
 *
 * - `promptTokens`   – tokens that belong to the request payload.
 * - `completionTokens` – tokens generated by the model.
 * - `totalTokens`    – sum of the two (convenient for UI aggregation).
 * - `costUsd`        – approximate cost in US dollars, calculated from
 *                      per‑model pricing (see LlmAction.computeCost).
 */
export interface LlmCostInfo {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  costUsd: number;
}