apiVersion: v1
kind: Service
metadata:
  name: {{ include "keep.fullname" . }}
  labels:
    {{- include "keep.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
    - port: 40000
      targetPort: 40000
      protocol: UDP
      name: udp
  selector:
    {{- include "keep.selectorLabels" . | nindent 4 }}