package com.axentx.surrogate1.alerts;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Component;

/**
 * Evaluates cost against a configured budget and sends an email alert if exceeded.
 * 
 * <p>Designed for use with scheduled tasks (e.g., {@code @Scheduled(fixedRate = 300_000)} for 5-min checks).
 * Ensures alerts are actionable, timely, and human-readable.
 */
@Component
public class CostThresholdAlert {

    private final JavaMailSender mailSender;
    private final String recipientEmail;
    private final double budget;

    public CostThresholdAlert(
            JavaMailSender mailSender,
            @Value("${alerts.cost.recipient}") String recipientEmail,
            @Value("${alerts.cost.budget}") double budget) {
        // Defensive validation: budget must be non-negative
        if (budget < 0) {
            throw new IllegalArgumentException("Budget must be non-negative: " + budget);
        }
        this.mailSender = mailSender;
        this.recipientEmail = recipientEmail;
        this.budget = budget;
    }

    /**
     * Evaluates the current cost and triggers an alert if budget is exceeded.
     * 
     * @param currentCost the latest observed cost (must be ≥ 0)
     * @throws IllegalArgumentException if currentCost < 0
     */
    public void evaluateCost(double currentCost) {
        if (currentCost < 0) {
            throw new IllegalArgumentException("Cost cannot be negative: " + currentCost);
        }

        if (currentCost > budget) {
            sendAlertEmail(currentCost);
        }
    }

    private void sendAlertEmail(double currentCost) {
        SimpleMailMessage message = new SimpleMailMessage();
        message.setTo(recipientEmail);
        message.setSubject("⚠️ Cost Threshold Exceeded: $" + String.format("%.2f", currentCost));
        message.setText(buildEmailBody(currentCost));
        mailSender.send(message);
    }

    private String buildEmailBody(double currentCost) {
        return String.join("\n",
            "ALERT: Cloud cost has exceeded the configured budget.",
            "",
            "Current cost: $" + String.format("%.2f", currentCost),
            "Budget limit: $" + String.format("%.2f", budget),
            "Overrun: $" + String.format("%.2f", currentCost - budget) + " (" + 
                String.format("%.1f", (currentCost / budget - 1) * 100) + "% over)",
            "",
            "Recommended actions:",
            "  1. Review recent AWS Cost Explorer reports.",
            "  2. Identify unexpected resource usage (e.g., idle EC2, untagged resources).",
            "  3. Enforce cost controls (e.g., tags, quotas, reserved instances).",
            "",
            "---",
            "Generated by surrogate-1 cost monitoring system. Do not reply."
        );
    }
}